# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'DouYuTV' do
  use_frameworks!
  #网络请求
  pod 'Alamofire', '~> 4.7.3'
  #json转model   '~> 4.2.0'
  pod 'HandyJSON', '5.0.0-beta'
  #下载网络图片
  pod 'Kingfisher', '~> 4.10.0'
  target 'DouYuTVTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DouYuTVUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
